from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect,
                          QSize, QTime, QUrl, Qt, QEvent, QTimer)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence,
                         QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PyQt5.QtWidgets import *
from model import run
from recognized import recognize
from encode import encodeListKnown


class Ui_MainWindow(QDialog):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 501)
        self.home = QtWidgets.QWidget(MainWindow)
        self.home.setObjectName("home")
        self.main_frame = QtWidgets.QFrame(self.home)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 751, 571))
        self.main_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.frame = QtWidgets.QFrame(self.main_frame)
        self.frame.setGeometry(QtCore.QRect(10, 10, 321, 481))
        self.frame.setStyleSheet("background-color: rgb(0, 132, 191);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.select_frame_1 = QtWidgets.QFrame(self.frame)
        self.select_frame_1.setGeometry(QtCore.QRect(20, 40, 261, 121))
        self.select_frame_1.setStyleSheet("background-color: rgb(21, 36, 255);")
        self.select_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_frame_1.setObjectName("select_frame_1")
        self.file_label = QtWidgets.QLabel(self.select_frame_1)
        self.file_label.setGeometry(QtCore.QRect(10, 20, 241, 21))
        self.file_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.file_label.setObjectName("file_label")
        self.selectVideo_btn = QtWidgets.QPushButton(self.select_frame_1)
        self.selectVideo_btn.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.selectVideo_btn.setStyleSheet("background-color: rgb(255, 255, 0);\n"
                                           "color: rgb(21, 36, 255);")
        self.selectVideo_btn.setObjectName("selectVideo_btn")
        self.selectVideoWit_label = QtWidgets.QLabel(self.select_frame_1)
        self.selectVideoWit_label.setGeometry(QtCore.QRect(90, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.selectVideoWit_label.setFont(font)
        self.selectVideoWit_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.selectVideoWit_label.setObjectName("selectVideoWit_label")
        self.done_label_1 = QtWidgets.QLabel(self.frame)
        self.done_label_1.setGeometry(QtCore.QRect(60, 160, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.done_label_1.setFont(font)
        self.done_label_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.done_label_1.setObjectName("done_label_1")
        self.select_frame_2 = QtWidgets.QFrame(self.frame)
        self.select_frame_2.setGeometry(QtCore.QRect(20, 210, 261, 91))
        self.select_frame_2.setStyleSheet("background-color: rgb(21, 36, 255);")
        self.select_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_frame_2.setObjectName("select_frame_2")
        self.encodeButton = QtWidgets.QPushButton(self.select_frame_2)
        self.encodeButton.setGeometry(QtCore.QRect(80, 20, 81, 23))
        self.encodeButton.setStyleSheet("background-color: rgb(255, 255, 0);\n"
                                        "color: rgb(21, 36, 255);")
        self.encodeButton.setObjectName("encodeButton")
        self.encodeLabel = QtWidgets.QLabel(self.select_frame_2)
        self.encodeLabel.setGeometry(QtCore.QRect(20, 40, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.encodeLabel.setFont(font)
        self.encodeLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.encodeLabel.setObjectName("encodeLabel")
        self.done_label_2 = QtWidgets.QLabel(self.frame)
        self.done_label_2.setGeometry(QtCore.QRect(40, 310, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.done_label_2.setFont(font)
        self.done_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.done_label_2.setObjectName("done_label_2")
        self.Videoanalizer_label = QtWidgets.QLabel(self.frame)
        self.Videoanalizer_label.setGeometry(QtCore.QRect(90, 0, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(14)
        self.Videoanalizer_label.setFont(font)
        self.Videoanalizer_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.Videoanalizer_label.setObjectName("Videoanalizer_label")
        self.widget = QtWidgets.QWidget(self.main_frame)
        self.widget.setGeometry(QtCore.QRect(350, 10, 391, 481))
        self.widget.setStyleSheet("background-color: rgb(0, 132, 191);")
        self.widget.setObjectName("widget")
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setGeometry(QtCore.QRect(10, 150, 371, 141))
        self.frame_4.setStyleSheet("background-color: rgb(21, 36, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.recognizedFile_label = QtWidgets.QLabel(self.frame_4)
        self.recognizedFile_label.setGeometry(QtCore.QRect(10, 10, 351, 31))
        self.recognizedFile_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.recognizedFile_label.setObjectName("recognizedFile_label")
        self.runRecognize_Button = QtWidgets.QPushButton(self.frame_4)
        self.runRecognize_Button.setGeometry(QtCore.QRect(130, 70, 101, 23))
        self.runRecognize_Button.setStyleSheet("background-color: rgb(255, 255, 0);\n"
                                               "color: rgb(21, 36, 255);")
        self.runRecognize_Button.setObjectName("runRecognize_Button")
        self.recognizedWait_label = QtWidgets.QLabel(self.frame_4)
        self.recognizedWait_label.setGeometry(QtCore.QRect(140, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.recognizedWait_label.setFont(font)
        self.recognizedWait_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.recognizedWait_label.setObjectName("recognizedWait_label")
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setGeometry(QtCore.QRect(10, 70, 371, 61))
        self.frame_5.setStyleSheet("background-color: rgb(21, 36, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.select_button = QtWidgets.QPushButton(self.frame_5)
        self.select_button.setGeometry(QtCore.QRect(130, 20, 101, 23))
        self.select_button.setStyleSheet("background-color: rgb(255, 255, 0);\n"
                                         "color: rgb(21, 36, 255);")
        self.select_button.setObjectName("select_button")
        self.faceRecognition_label = QtWidgets.QLabel(self.widget)
        self.faceRecognition_label.setGeometry(QtCore.QRect(130, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(14)
        self.faceRecognition_label.setFont(font)
        self.faceRecognition_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.faceRecognition_label.setObjectName("faceRecognition_label")
        self.frame_6 = QtWidgets.QFrame(self.widget)
        self.frame_6.setGeometry(QtCore.QRect(10, 300, 371, 141))
        self.frame_6.setStyleSheet("background-color: rgb(21, 36, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.recognized_label_2 = QtWidgets.QLabel(self.frame_6)
        self.recognized_label_2.setGeometry(QtCore.QRect(140, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.recognized_label_2.setFont(font)
        self.recognized_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.recognized_label_2.setObjectName("recognized_label_2")
        self.timestamp_label = QtWidgets.QLabel(self.frame_6)
        self.timestamp_label.setGeometry(QtCore.QRect(20, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.timestamp_label.setFont(font)
        self.timestamp_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.timestamp_label.setObjectName("timestamp_label")
        self.timestamp_label_2 = QtWidgets.QLabel(self.frame_6)
        self.timestamp_label_2.setGeometry(QtCore.QRect(140, 40, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.timestamp_label_2.setFont(font)
        self.timestamp_label_2.setObjectName("timestamp_label_2")
        MainWindow.setCentralWidget(self.home)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_label.setText(_translate("MainWindow", ""))
        self.selectVideo_btn.setText(_translate("MainWindow", "Select Video"))
        self.selectVideoWit_label.setText(_translate("MainWindow", "Please wiat"))
        self.done_label_1.setText(_translate("MainWindow", "Done. Faces has been saved"))
        self.encodeButton.setText(_translate("MainWindow", "Encode Faces"))
        self.encodeLabel.setText(_translate("MainWindow", "Encoding.. This might take a while"))
        self.done_label_2.setText(_translate("MainWindow", "Done. Faces has been encoded"))
        self.Videoanalizer_label.setText(_translate("MainWindow", "Video Analizer"))
        self.recognizedFile_label.setText(_translate("MainWindow", "File"))
        self.runRecognize_Button.setText(_translate("MainWindow", "Run recognizer"))
        self.recognizedWait_label.setText(_translate("MainWindow", "Please wiat"))
        self.select_button.setText(_translate("MainWindow", "Select Image"))
        self.faceRecognition_label.setText(_translate("MainWindow", "Face Recognition"))
        self.recognized_label_2.setText(_translate("MainWindow", "Recognized"))
        self.timestamp_label.setText(_translate("MainWindow", "Timestamp(s):"))
        self.timestamp_label_2.setText(_translate("MainWindow", "."))
        self.done_label_1.hide()
        self.done_label_2.hide()
        self.selectVideoWit_label.hide()
        self.encodeLabel.hide()
        self.select_frame_2.hide()
        self.frame_6.hide()
        self.frame_4.hide()
        self.selectVideo_btn.clicked.connect(self.browseFiles)
        self.encodeButton.clicked.connect(self.encodeFiles)
        self.select_button.clicked.connect(self.loadFiles)
        self.runRecognize_Button.clicked.connect(self.recognizeFiles)

    def browseFiles(self):
        self.select_frame_2.hide()
        self.file_label.hide()
        self.selectVideo_btn.hide()
        self.done_label_2.hide()
        filename = QFileDialog.getOpenFileName(self, 'Open file', 'D:', 'Video (*.mp4 *.3gp *.hd)')
        self.file_label.hide()
        self.selectVideo_btn.hide()
        self.selectVideoWit_label.show()
        QTimer.singleShot(1000, lambda: run(filename[0]))
        self.file_label.setText(filename[0])
        self.file_label.show()
        self.selectVideo_btn.show()
        self.selectVideoWit_label.hide()
        self.select_frame_2.show()

    def encodeFiles(self):
        self.encodeLabel.hide()
        self.done_label_2.hide()
        self.encodeLabel.show()
        self.encodeButton.hide()
        QTimer.singleShot(1000, lambda: encodeListKnown())
        self.done_label_2.show()
        self.encodeLabel.hide()
        self.encodeButton.show()

    def loadFiles(self):
        self.recognizedWait_label.hide()
        self.frame_4.show()
        global recognizeFilename
        recognizeFilename = QFileDialog.getOpenFileName(self, 'Open file', 'D:', 'Image (*.png *.jpg *.jpeg)')
        self.frame_4.show()
        self.recognizedFile_label.setText(recognizeFilename[0])
        self.recognizedFile_label.show()

    def recognizeFiles(self):
        self.frame_6.hide()
        self.runRecognize_Button.hide()
        self.recognizedWait_label.show()
        runModel = recognize(recognizeFilename[0])
        print(runModel)
        if runModel != "NOT IDENTIFIED":
            self.frame_6.show()
            self.timestamp_label.show()
            self.timestamp_label_2.show()
            self.timestamp_label_2.setText('Seen in ' + runModel + ' seconds')
            self.runRecognize_Button.show()
            self.frame_4.hide()
            self.recognizedFile_label.hide()
            self.recognizedWait_label.hide()

        else:
            self.runRecognize_Button.show()
            self.frame_4.hide()
            self.recognizedFile_label.hide()
            self.recognizedWait_label.hide()
            mes = QMessageBox()
            mes.setWindowTitle("Results")
            mes.setText("User not Identified")
            mes.setIcon(QMessageBox.Critical)
            x = mes.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
